# Generated by Django 4.1.7 on 2023-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('UD', 'Undecided')], default='UD', max_length=2)),
            ],
        ),
    ]
